---
# tasks file for openldap
- name: openldap install
  apt: name={{ item }} state=present update_cache=yes
  with_items: 
      - slapd
      - ldap-utils
      - python-ldap
      - phpldapadmin
      
- name: phpldapadmin config
  template: src=config.php.j2 dest=/etc/phpldapadmin/config.php state=present backup=yes
  
- name: ssl directory create
  file: path=/etc/apache2/ssl state=directory owner=root group=root mode=755

- name: ssl cert create
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt
