---
# tasks file for oracle-java
- name: pre-accept oracle java 8 license
  debconf: name='oracle-java8-installer' 
    question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'  

- name: install oracle java 8
  apt: name={{item}} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default