---
# tasks file for bash
- name: enable skel color
  lineinfile: dest=/etc/skel/.bashrc regexp="^#force_color_prompt" 
    line="force_color_prompt=yes" state=present
  when: inventory_hostname in groups.bash
  
- name: enable root user color
  lineinfile: dest=/root/.bashrc regexp="^#force_color_prompt" 
    line="force_color_prompt=yes" state=present
  when: inventory_hostname in groups.bash
  
- name: enable root user color red
  lineinfile: dest=/root/.bashrc regexp="^PS1" 
    line="PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" 
    state=present
  when: inventory_hostname in groups.bash
  
- name: find exiting users home directories
  find: paths="/home" patterns="*" file_type=directory
  register: homedirs
  when: inventory_hostname in groups.bash
  
- name: enable exiting users color
  lineinfile: dest="{{ item.path }}/.bashrc" regexp="^#force_color_prompt" 
    line="force_color_prompt=yes" state=present
  with_items: "{{ homedirs.files }}"
  when: inventory_hostname in groups.bash
