---
# tasks file for cups
- name: cups install
  apt: name=cups  state=present update_cache=yes cache_valid_time=86400
  when: inventory_hostname in groups.cups
  
- name: create ppd directory
  file: path={{ ppd_directory }} owner=root group=lp mode=0755 state=directory
  when: inventory_hostname in groups.cups
  
- name: add ppd files
  copy: src={{ item }} dest={{ cups_ppd_directory }} owner=root group=root mode=0644
  with_items:
    - Canon_iR1730.ppd
    - Canon_imageRUNNER1133_series.ppd
    - Samsung_ML-2580N.ppd
  when: inventory_hostname in groups.cups
  
- name: cups conf
  template: src=cupsd.conf.j2 dest=/etc/cups/cupsd.conf owner=root group=root mode=0644
  when: inventory_hostname in groups.cups
  notify: cups restart
  
- name: cups status
  service: name=cups state=restarted enabled=true
  when: inventory_hostname in groups.cups