---
# tasks file for kvm
- name: kvm install
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - qemu-kvm
      - libvirt-bin
      - libvirt-dev
      - ubuntu-vm-builder
      - bridge-utils
  notify: libvirt restart
  tags: [ 'packages' ]

- name: virtual machine manager install
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - virt-manager
    - qemu-system
  when: "'{{ansible_hostname}}' in groups['dev']"
  tags: [ 'packages' ]
