---
- name: restart apache
  service: name=apache2 state=restarted

# restart smokeping (tried reload instead but it seems it did not work)
- name: restart smokeping
  service: name=smokeping state=restarted
