---

- name: Install Postfix base packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items:
    - [ 'postfix', 'postfix-pcre', 'bsd-mailx', 'make' ]
    - '{{ postfix_packages }}'
  when: item is defined and item

- name: Purge other SMTP servers
  apt:
    name: '{{ item }}'
    state: 'absent'
    purge: True
  with_items: '{{ postfix_purge_packages }}'
  when: postfix_purge_packages|d()

- name: Disable Postfix configuration in debconf
  debconf:
    name: 'postfix'
    question: 'postfix/main_mailer_type'
    vtype: 'select'
    value: 'No configuration'

- name: Divert original Postfix configuration
  command: dpkg-divert --quiet --local --divert /etc/postfix/{{ item }}.dpkg-divert --rename /etc/postfix/{{ item }}
           creates=/etc/postfix/{{ item }}.dpkg-divert
  with_items: [ 'main.cf', 'master.cf' ]
  notify: [ 'Check postfix and restart' ]

- name: Divert original aliases database
  command: dpkg-divert --quiet --local --divert /etc/aliases.dpkg-divert --rename /etc/aliases
           creates=/etc/aliases.dpkg-divert

