---
# tasks file for rundeck

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - rundeck

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - rundeck

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - rundeck

- name: Ensure Rundeck is started and enabled on boot
  become: yes
  service:
    name: "{{ rundeck_service_name }}"
    state: started
    enabled: yes
  tags:
    - rundeck
