---

dependencies: []

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and manage PHP5 environment using php5-fpm'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - development
  - system
  - web

