---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-owncloud"
  git_branch: "master"
  galaxy_id: "1584"

  beta: false
  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Hartmut Goebel'
      url: 'http://www.crazy-compilers.com/'
      email: 'h.goebel@crazy-compilers.com'
      github: 'htgoebel'

    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    This role installs a [ownCloud](https://owncloud.org/) instance on a
    specified host, either with SQLite, MySQL, MariaDB or PostgreSQL database
    as a backend and an nginx webserver as a frontend.

    Only ownCloud 8.0 and later are supported because for older
    versions there are no complete deb-packages available.

