---
# handlers file for asterisk
- name: enable mariadb
  service: name=mariadb state=restarted

- name: asterisk stop
  service: name=asterisk state=stopped
    
- name: asterisk restarted
  service: name=asterisk state=restarted 
  
- name: restart apache2
  service: name=apach2 state=restarted 
    
- name: asterisk start
  service: name=asterisk state=start

- name: asterisk status
  service: name=asterisk state=running