---
#- name: create ansible user
#  user: name=ansible state=present system=yes shell=/bin/bash 
#    group=sudo
- name: ansible install
  apt: name=ansible state=present update_cache=yes cache_valid_time=86400
  when: "'{{inventory_hostname_short}}' in groups['ansible-controllers']"
  tags: [ 'packages' ]
  
- name: use hashed out cfg and hosts files
  template: src={{item}}.j2 dest=/etc/ansible/{{item}}
  with_items:
    - ansible.cfg
    - hosts
  when: "'{{inventory_hostname_short}}' in groups['ansible-controllers']"
  
- name: install ansible controller requirements
  apt: name={{item}}  state=present update_cache=true cache_valid_time=86400
  with_items:
    - python-simplejson
    - python-yaml
    - python-jinja2
    - python-httplib2
    - python-six
    - python-paramiko
  when: "'{{inventory_hostname_short}}' in groups['ansible-controllers']"
  tags: [ 'packages' ]
          