---
# tasks file for server

# stalls on 16.04
#- name: basic ubuntu server install
#  command: tasksel install server
#  tags: [ 'packages' ]

- name: install several tools
  apt: name={{item}} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - lsb-core
    - aptitude
    - debconf
    - debconf-utils
    - libxml2-dev
    - libxslt1-dev
    - pkg-config
    - binutils
    - libreadline5
    - ruby
    - ssl-cert
    - unhide.rb
    - lynx
    - pv
    - netcat
    - htop
    - ncdu
    - tar
    - gzip
    - zip
    - unzip
    - bzip2
    - p7zip
    - rar
    - unrar
    - iwatch
    - xz-utils
  tags: [ 'packages' ]