---
- hosts: database
  become: true
  gather_facts: no
  tasks:
    - name: Setup php5-fpm pool configuration
      template:
        src: 'etc/php5/fpm/pool-available.d/pool.conf.j2'
        dest: '/etc/php5/fpm/pool-available.d/{{ item.name }}.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      with_items: 
        - php5_pools
      notify: reload php5-fpm

    - name: Enable php5-fpm pools
      file:
        path: '/etc/php5/fpm/pool.d/{{ item.name }}.conf'
        src: '/etc/php5/fpm/pool-available.d/{{ item.name }}.conf'
        state: 'link'
        owner: 'root'
        group: 'root'
        mode: '0644'
      with_items: 
        - php5_pools
      when: item.enabled is not defined or item.enabled == True
      notify: restart php5-fpm

    - name: Disable php5-fpm pools
      file:
        path: '/etc/php5/fpm/pool.d/{{ item.name }}.conf'
        state: 'absent'
      with_items:
         - php5_pools
      when: item.enabled is defined and item.enabled == False
      notify: restart php5-fpm

