---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-mariadb"
  git_branch: "master"
  galaxy_id: '4207'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [MariaDB](http://mariadb.org/) is a popular relational SQL database that
    was forked from MySQL server. Ansible roles `debops.mariadb` and
    `debops.mariadb_server` allow you to manage a MariaDB server and / or
    access it remotely from other hosts.
    
    `debops.mariadb` role is the "client" part - it installs `mariadb-client`
    Debian package, and uses Ansible delegation to configure users and databases in
    local or remote MariaDB servers. You can use `debops.mariadb_server` role to
    manage the MariaDB server itself.

