---

dependencies:

  - role: debops.secret
    tags: [ 'depend::secret', 'depend::secret:mariadb',
            'depend-of::mariadb', 'type::dependency:hard' ]

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and manage a MariaDB / MySQL client'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.8.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - 'database:sql'
  - 'system'

