## YAML Template.
---
- hosts: '{{ target }}'
  become: true

  tasks:
  
  - name: update
    apt: update_cache=yes cache_valid_time=86400
      
  - name: upgrade
    apt: upgrade=full autoremove=yes
