---
# handlers file for ha-proxy
- name: haproxy restart
  service: name=haproxy state=restarted

- name: haproxy start
  service: name=haproxy state=started

- name: haproxy stop
  service: name=haproxy state=stopped
