---
# handlers file for ubiquiti-unify
- name: apt-get update
  apt: update_cache=yes cache_valid_time=86400
  
- name: unifi restart
  service: name=unifi state=restarted
  
- name: restart mongodb
  service: name=mondodb state=restarted