#Bring stack down
- hosts: '{{ target }}'
  become: true
  tasks:
    - service: name=apache2 state=stopped

#Bring stack up
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=started

