---
- hosts: '{{ target }}'
  become: true
  tasks:

    - name: set hostname facts
      set_fact:
        full_hostname="{{ inventory_hostname}}"
#        short_hostname="{{ inventory_hostname.split('.', 1)[0] }}"

# " Double-quote for fixing vim highlighting

#    - name: set hostname
#      hostname:
#        name={{ short_hostname }}

#    - name: add hostname to /etc/hosts
#      lineinfile:
#        dest=/etc/hosts
#        line='{{ ansible_eth0.ipv4.address }} {{ full_hostname }}'
#        regexp=^bind-address
#         insertafter='^ansible_eth0.ipv4.address'
#        state=present
#
    - name: add hostname to /etc/hosts
      lineinfile:
        dest=/etc/hosts
        line='{{ ansible_eth0.ipv4.address }} {{ full_hostname }}'
        insertafter='^127\.0\.0\.1'
        state=present
#        regexp='^127\.0\.0\.1'
#        insertafter='^127\.0\.0\.1'
#        state=absent

