---
#Bring Stack Down
- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=stopped
 
#Restart mysql
- hosts: database
  become: true
  tasks:
    - service: name=mysql state=restarted

#Bring stack up
- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=started
 
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=started

