---
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - name: verify nginx service 
      service: name=nginx state=running
      changed_when: false

  
- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: verify apache2 service 
      service: name=apache2 state=running
      changed_when: false

    - name: verify apache2 is listening on 80
      wait_for: port=80 timeout=1
     


- hosts: database
  become: true
  gather_facts: false
  tasks:
    - name: verify mysql service 
      command: service mysql status
      changed_when: false

    - name: verify mysq is listening on 3306
      wait_for: port=3306 timeout=1
      
    

   
