---
# tasks file for desktop
- name: check if first run or not
  stat: path=/etc/lightdm/lightdm.conf.d/50-no-guest.conf.j2
  register: firstrun
  
- name: install basics
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - lsb-core
    - cpu-checker
    - curl
    - lynx
    - vim
    - screen
    - tar
    - gzip
    - zip
    - unzip
    - bzip2
    - p7zip
    - rar
    - unrar
    - ubuntu-restricted-extras
    - msttcorefonts
    - chromium-browser
    - evince

- name: install ops programs
  apt: name={{item}} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - nmap
    - netcat
    - netstat
    - whois
    - dnsutils
    - mtr-tiny
    - sshfs
    - traceroute
    - rdesktop
    - system-config-kickstart
  when: inventory_hostname in groups.wks_ops
  
- name: install dev programs
  apt: name={{item}} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - grc
    - pv
    - libboost-all-dev
    - libmodbus-dev
    - build-essential
    - autoconf
    - automake
    - autotools-dev
    - dh-make
    - debhelper
    - devscripts
    - fakeroot
    - lintian
    - pbuilder
    - uuid-dev
    - libssl-dev
    - libboost-all-dev
    - libpoco-dev
    - sqlite3
    - pkg-config
    - libtool
    - amqp-tools
    - terminator
    - meld
    - gitk
    - mysql-workbench
  when: inventory_hostname in groups.wks_dev or inventory_hostname in groups.wks_ops

- name: create project folder
  file: path=/home/{{ user }}/project state=directory mode=0755
  become_user: "{{ user }}"
  when: inventory_hostname in groups.wks_dev or inventory_hostname in groups.wks_ops
  
- name: remove www folder
  file: dest=/var/www  state=absent
  become: true
  when: inventory_hostname in groups.wks_dev or inventory_hostname in groups.wks_ops
  
- name: link project to var www
  file: dest=/var/www src=/home/{{ user }}/project owner={{ user }} group={{ user }}
    state=link mode=0755
  become: true
  when: inventory_hostname in groups.wks_dev or inventory_hostname in groups.wks_ops
  
- name: remove unwanted packages
  apt: name={{item}} state=absent purge=yes 
  with_items:
    - skype
    - thunderbird
    - adobereader-enu
#    Evolution Mail, will also remove Ekiga (VoIP client)
    - evolution-common
    - evolution-data-server
    - evolution-exchange
    - evolution-plugins
    - evolution-webcal
#    Panel applet to search Evolution address book
    - contact-lookup-applet
#    Mark Pilgrim’s Python tutorial
    - diveintopython
#    Example content for various desktop apps
    - example-content
#    Gnome games and associated data    
    - gnome-games gnome-games-data gnome-cards-data
#    Transmission BitTorrent client
    - transmission-common transmission-gtk
#    Openoffice.org productivity suite
#    - openoffice.org-calc 
#    - openoffice.org-draw 
#    - openoffice.org-impress 
#    - openoffice.org-writer 
#    - openoffice.org-base-core
#    Speech synthesizer (text to voice)
    - espeak
    - espeak-data
    - libespeak1
    - libgnome-speech7
#    Various accessibility functions
    - gnome-orca
    - brltty
    - brltty-x11
    - gnome-accessibility-themes
    - gnome-mag
    - libgnome-mag2
#    Assorted Arabic/Asian language font types
    - ttf-arabeyes
    - ttf-arphic-uming
    - ttf-indic-fonts-core
    - ttf-kochi-gothic
    - ttf-kochi-mincho
    - ttf-lao
    - ttf-malayalam-fonts
    - ttf-thai-tlwg
    - ttf-unfonts-core

- name: remove unity launcher icons
  file: path={{item}} state=absent
  with_items:
    - /usr/share/applications/ubuntu-amazon-default.desktop

# not sure this is needed anymore to check
#- name: enable to play DVD's
#  shell: /usr/share/doc/libdvdread4/install-css.sh
#  when: firstrun.stat.exists == False
  
# ALWAYS DO THIS LAST AS WE CHECK AT THE START
- name: disable guest session 
  template: src=50-no-guest.conf.j2  dest=/etc/lightdm/lightdm.conf.d/50-no-guest.conf
  when: inventory_hostname in groups.wks
